---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: false
  tags: always

  tasks:
    - name: Update cache & upgrade all packages
      raw: apt-get update && apt-get upgrade -y
      changed_when: false

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || apt-get install -y python-minimal
      changed_when: false
