---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search_engine
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: search_engine
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: rabbitmq
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: rabbitmq
          protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{  .Values.rabbitmqDefaultUser | default "test" | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{  .Values.rabbitmqDefaultPass | default "test" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
