---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search_engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search_engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{  .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.mongoPort | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{  .Values.rmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{  .Values.rmqQueue | default "mqqueue" | quote }}
        - name: RMQ_USERNAME
          value: {{  .Values.rmqUsername | default "test" | quote }}
        - name: RMQ_PASSWORD
          value: {{  .Values.rmqPassword | default "test" | quote }}
        - name: CHECK_INTERVAL
          value: {{  .Values.chechInterval | default "10" | quote }}
        - name: EXCLUDE_URLS
          value: {{  .Values.excludeUrls | default ".*github.com" | quote }}
        - name: URL
          value: {{  .Values.startUrl | default "https://vitkhab.github.io/search_engine_test_site/" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
